### ISSUE TITLE
[BUG] Windows installer not available for 1.6.2

### ISSUE THREAD

**Issue by modem7** [francescmm/GitQlient#283]
**Describe the bug**
Windows installer not available for 1.6.2.

Last available is 1.6.0. Possible workflow issue?

**Comment by francescmm** [comment]
Hi @modem7, I'm aware of the Windows "issue". The problem is that I cannot ship the installer I was using before for license issues, so I need to check if I can get a new one.

Installing all Qt dependencies manually is quite tedious on Windows so I'd prefer to avoid that pain to the user.

Let's see what I can do, and sorry for the trouble! :)

**Comment by jo-chemla** [comment]
Releasing GitQlient as a [winget-pkgs](https://github.com/microsoft/winget-pkgs) package would enable you to specify Qt as a dependency - eg the way this is done [here](https://github.com/microsoft/winget-pkgs/blob/272ec0d8bd0abf5889f7c82793e4c9569e16898f/manifests/m/MartiCliment/UniGetUI/3.1.3/MartiCliment.UniGetUI.installer.yaml#L19-L24) for dependencies of UnigetUI. 

```yaml
# installer.yaml

# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json
PackageIdentifier: MartiCliment.UniGetUI
PackageVersion: 3.1.3
# ...
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
    MinimumVersion: 14.40.33816.0
# ...
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/marticliment/UniGetUI/releases/download/3.1.3/UniGetUI.Installer.exe
  InstallerSha256: 58AE121CD325B7F5AEF6ED07E21D72A89BA0E7FF6ADDB2FB339A69DCFEFAD6B4
  # ...
```

If this is helpful, I can publish the initial manifest release for 1.6.0 using [Komac](https://github.com/russellbanks/Komac), then you could define a github-action workflow based on [winget-releaser-v2](https://github.com/vedantmgoyal9/winget-releaser) - again [this example](https://github.com/marticliment/UniGetUI/blob/main/.github/workflows/winget-stable.yml) from UnigetUI is useful. 

```yaml
name: Publish stable releases to WinGet
on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: francescmm.GitQlient # use your identifier
          version: ${{ github.event.release.tag_name }}
          token: ${{ secrets.WINGET_TOKEN }} # and token
          installers-regex: '\.exe$' # Only .exe files
```
